-- ============================================
-- CAFE POS & INVENTORY MANAGEMENT SYSTEM
-- Supabase/Postgres-compatible schema + seed
-- ============================================

-- Enum types (idempotent)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_type_enum') THEN
        CREATE TYPE order_type_enum AS ENUM ('dine_in','take_out');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method_enum') THEN
        CREATE TYPE payment_method_enum AS ENUM ('cash','card','gcash','maya');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status_enum') THEN
        CREATE TYPE order_status_enum AS ENUM ('pending','completed','cancelled','refunded');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'inventory_log_type_enum') THEN
        CREATE TYPE inventory_log_type_enum AS ENUM ('restock','sale','adjustment','waste');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role_enum') THEN
        CREATE TYPE user_role_enum AS ENUM ('admin','staff');
    END IF;
END $$;

-- Updated-at trigger helper
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    icon varchar(50) DEFAULT 'coffee',
    created_at timestamptz DEFAULT now()
);

-- Products / Menu Items Table
CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint,
    name varchar(150) NOT NULL,
    description text,
    price numeric(10,2) NOT NULL DEFAULT 0.00,
    cost numeric(10,2) NOT NULL DEFAULT 0.00,
    stock integer NOT NULL DEFAULT 0,
    low_stock_threshold integer DEFAULT 10,
    unit varchar(30) DEFAULT 'pcs',
    size varchar(20) NOT NULL DEFAULT 'Regular',
    image_url text,
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Customers Table
CREATE TABLE IF NOT EXISTS customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150),
    email varchar(150),
    phone varchar(30),
    created_at timestamptz DEFAULT now()
);

-- Users Table (for POS accounts)
CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(120) NOT NULL,
    username varchar(80) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    role user_role_enum NOT NULL DEFAULT 'staff',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz DEFAULT now()
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number varchar(20) NOT NULL UNIQUE,
    customer_id bigint DEFAULT NULL,
    cashier_id bigint DEFAULT NULL,
    customer_name varchar(150) DEFAULT 'Walk-in',
    order_type order_type_enum DEFAULT 'dine_in',
    subtotal numeric(10,2) DEFAULT 0.00,
    discount numeric(10,2) DEFAULT 0.00,
    tax numeric(10,2) DEFAULT 0.00,
    total numeric(10,2) DEFAULT 0.00,
    payment_method payment_method_enum DEFAULT 'cash',
    amount_paid numeric(10,2) DEFAULT 0.00,
    change_given numeric(10,2) DEFAULT 0.00,
    status order_status_enum DEFAULT 'pending',
    notes text,
    created_at timestamptz DEFAULT now(),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
    CONSTRAINT fk_orders_cashier
        FOREIGN KEY (cashier_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint DEFAULT NULL,
    product_name varchar(150) NOT NULL,
    variant_name varchar(50),
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
);

-- Inventory Logs Table
CREATE TABLE IF NOT EXISTS inventory_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL,
    type inventory_log_type_enum NOT NULL,
    quantity_change integer NOT NULL,
    quantity_before integer NOT NULL,
    quantity_after integer NOT NULL,
    notes varchar(255),
    created_at timestamptz DEFAULT now(),
    CONSTRAINT fk_inventory_logs_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint DEFAULT NULL,
    user_name varchar(120) DEFAULT NULL,
    action_text varchar(255) NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- Ingredients Table
CREATE TABLE IF NOT EXISTS ingredients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL UNIQUE,
    unit varchar(30) NOT NULL DEFAULT 'g',
    stock numeric(12,2) NOT NULL DEFAULT 0.00,
    low_stock_threshold numeric(12,2) NOT NULL DEFAULT 0.00,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

CREATE TRIGGER trg_ingredients_updated_at
BEFORE UPDATE ON ingredients
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Product Variants Table (sizes with individual pricing)
CREATE TABLE IF NOT EXISTS product_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL,
    size_label varchar(50) NOT NULL DEFAULT 'Regular',
    price numeric(10,2) NOT NULL DEFAULT 0.00,
    stock integer NOT NULL DEFAULT 0,
    low_stock_threshold integer DEFAULT 5,
    is_active boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT fk_product_variants_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TRIGGER trg_product_variants_updated_at
BEFORE UPDATE ON product_variants
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Product Ingredients / Recipe Table
CREATE TABLE IF NOT EXISTS product_ingredients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    quantity_required numeric(12,2) NOT NULL DEFAULT 0.00,
    created_at timestamptz DEFAULT now(),
    CONSTRAINT uniq_product_ingredient UNIQUE (product_id, ingredient_id)
);

CREATE INDEX IF NOT EXISTS idx_pi_product ON product_ingredients(product_id);
CREATE INDEX IF NOT EXISTS idx_pi_ingredient ON product_ingredients(ingredient_id);

-- Product Variant Ingredients / Recipe Table
CREATE TABLE IF NOT EXISTS product_variant_ingredients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    quantity_required numeric(12,2) NOT NULL DEFAULT 0.00,
    created_at timestamptz DEFAULT now(),
    CONSTRAINT uniq_variant_ingredient UNIQUE (variant_id, ingredient_id)
);

CREATE INDEX IF NOT EXISTS idx_pvi_variant ON product_variant_ingredients(variant_id);
CREATE INDEX IF NOT EXISTS idx_pvi_ingredient ON product_variant_ingredients(ingredient_id);

-- ============================================
-- SAMPLE DATA (idempotent)
-- ============================================

INSERT INTO categories (name, icon)
SELECT v.name, v.icon
FROM (VALUES
    ('Coffee', 'coffee'),
    ('Tea', 'leaf'),
    ('Pastries', 'cake'),
    ('Sandwiches', 'sandwich'),
    ('Cold Drinks', 'glass-water'),
    ('Merchandise', 'shopping-bag')
) AS v(name, icon)
WHERE NOT EXISTS (
    SELECT 1 FROM categories c WHERE c.name = v.name
);

INSERT INTO products (category_id, name, description, price, cost, stock, low_stock_threshold, unit)
SELECT c.id, v.name, v.description, v.price, v.cost, v.stock, v.low_stock_threshold, v.unit
FROM (VALUES
    ('Coffee', 'Espresso', 'Single shot of rich espresso', 90.00, 25.00, 100, 20, 'cup'),
    ('Coffee', 'Americano', 'Espresso with hot water', 110.00, 30.00, 100, 20, 'cup'),
    ('Coffee', 'Cappuccino', 'Espresso with steamed milk foam', 145.00, 40.00, 80, 15, 'cup'),
    ('Coffee', 'Latte', 'Espresso with steamed milk', 155.00, 42.00, 80, 15, 'cup'),
    ('Coffee', 'Flat White', 'Double ristretto with microfoam', 165.00, 45.00, 60, 10, 'cup'),
    ('Coffee', 'Cold Brew', '12-hour cold brewed coffee', 175.00, 50.00, 40, 8, 'cup'),
    ('Tea', 'Matcha Latte', 'Premium matcha with oat milk', 175.00, 55.00, 50, 10, 'cup'),
    ('Tea', 'Chamomile Tea', 'Soothing chamomile blend', 95.00, 20.00, 60, 10, 'cup'),
    ('Tea', 'Earl Grey', 'Classic bergamot tea', 95.00, 20.00, 60, 10, 'cup'),
    ('Pastries', 'Croissant', 'Butter croissant, freshly baked', 85.00, 35.00, 30, 5, 'pcs'),
    ('Pastries', 'Banana Bread', 'House-made banana loaf', 95.00, 38.00, 20, 5, 'slice'),
    ('Pastries', 'Chocolate Muffin', 'Double chocolate chip muffin', 90.00, 35.00, 25, 5, 'pcs'),
    ('Sandwiches', 'Club Sandwich', 'Turkey, bacon, lettuce, tomato', 215.00, 85.00, 20, 5, 'pcs'),
    ('Sandwiches', 'Avocado Toast', 'Sourdough with smashed avocado', 195.00, 75.00, 15, 5, 'pcs'),
    ('Cold Drinks', 'Iced Latte', 'Espresso over ice with milk', 155.00, 42.00, 80, 15, 'cup'),
    ('Cold Drinks', 'Iced Matcha', 'Matcha over ice with oat milk', 175.00, 55.00, 50, 10, 'cup'),
    ('Cold Drinks', 'Sparkling Water', 'San Pellegrino 500ml', 75.00, 30.00, 48, 10, 'bottle'),
    ('Merchandise', 'Tote Bag', 'Canvas cafe branded tote', 350.00, 120.00, 15, 3, 'pcs'),
    ('Merchandise', 'Coffee Beans 250g', 'Single origin house blend', 450.00, 200.00, 10, 3, 'bag')
) AS v(category_name, name, description, price, cost, stock, low_stock_threshold, unit)
JOIN categories c ON c.name = v.category_name
WHERE NOT EXISTS (
    SELECT 1 FROM products p WHERE p.name = v.name
);

INSERT INTO ingredients (name, unit, stock, low_stock_threshold) VALUES
    ('Coffee Beans', 'g', 10000, 1500),
    ('Milk', 'ml', 20000, 3000),
    ('Water', 'ml', 100000, 15000),
    ('Ice', 'g', 20000, 3000)
ON CONFLICT (name) DO UPDATE SET
    unit = EXCLUDED.unit,
    stock = EXCLUDED.stock,
    low_stock_threshold = EXCLUDED.low_stock_threshold;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 18
FROM products p
JOIN ingredients i ON i.name = 'Coffee Beans'
WHERE p.name = 'Espresso'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 40
FROM products p
JOIN ingredients i ON i.name = 'Water'
WHERE p.name = 'Espresso'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 18
FROM products p
JOIN ingredients i ON i.name = 'Coffee Beans'
WHERE p.name = 'Americano'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 180
FROM products p
JOIN ingredients i ON i.name = 'Water'
WHERE p.name = 'Americano'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 18
FROM products p
JOIN ingredients i ON i.name = 'Coffee Beans'
WHERE p.name = 'Cappuccino'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 150
FROM products p
JOIN ingredients i ON i.name = 'Milk'
WHERE p.name = 'Cappuccino'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 18
FROM products p
JOIN ingredients i ON i.name = 'Coffee Beans'
WHERE p.name = 'Latte'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 220
FROM products p
JOIN ingredients i ON i.name = 'Milk'
WHERE p.name = 'Latte'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 20
FROM products p
JOIN ingredients i ON i.name = 'Coffee Beans'
WHERE p.name = 'Flat White'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 180
FROM products p
JOIN ingredients i ON i.name = 'Milk'
WHERE p.name = 'Flat White'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 30
FROM products p
JOIN ingredients i ON i.name = 'Coffee Beans'
WHERE p.name = 'Cold Brew'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 250
FROM products p
JOIN ingredients i ON i.name = 'Water'
WHERE p.name = 'Cold Brew'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 120
FROM products p
JOIN ingredients i ON i.name = 'Ice'
WHERE p.name = 'Cold Brew'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 18
FROM products p
JOIN ingredients i ON i.name = 'Coffee Beans'
WHERE p.name = 'Iced Latte'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 200
FROM products p
JOIN ingredients i ON i.name = 'Milk'
WHERE p.name = 'Iced Latte'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;

INSERT INTO product_ingredients (product_id, ingredient_id, quantity_required)
SELECT p.id, i.id, 120
FROM products p
JOIN ingredients i ON i.name = 'Ice'
WHERE p.name = 'Iced Latte'
ON CONFLICT (product_id, ingredient_id)
DO UPDATE SET quantity_required = EXCLUDED.quantity_required;
